In [19]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [2]:
blood = pd.read_csv("data/medicaldata_blood_storage.csv")
blood

RBC.Age.Group  Median.RBC.Age   Age  AA  FamHx   PVol  TVol  T.Stage  \
0                3              25  72.1   0      0   54.0   3.0      1.0   
1                3              25  73.6   0      0   43.2   3.0      2.0   
2                3              25  67.5   0      0  102.7   1.0      1.0   
3                2              15  65.8   0      0   46.0   1.0      1.0   
4                2              15  63.2   0      0   60.0   2.0      1.0   
..             ...             ...   ...  ..    ...    ...   ...      ...   
311              1              10  54.8   0      0   25.6   2.0      1.0   
312              3              25  62.3   1      0   42.3   2.0      1.0   
313              3              25  62.4   1      0   50.0   2.0      NaN   
314              2              15  57.6   0      0   74.9   1.0      1.0   
315              3              25  59.9   0      1   54.1   3.0      1.0   

     bGS  BN+  OrganConfined  PreopPSA  PreopTherapy  Units  sGS  \
0    3.0    0              0     14.08             1      6    1   
1    2.0    0              1     10.50             0      2    3   
2    3.0    0              1      6.98             1      1    1   
3    1.0    0              1      4.40             0      2    3   
4    2.0    0              1     21.40             0      3    3   
..   ...  ...            ...       ...           ...    ...  ...   
311  1.0    0              1      5.00             0      1    3   
312  1.0    0              1      7.60             0      1    2   
313  1.0    0              0      9.30             0      2    3   
314  1.0    0              1      4.50             0      2    2   
315  1.0    0              1      6.80             0      1    3   

     AnyAdjTherapy  AdjRadTherapy  Recurrence  Censor  TimeToRecurrence  
0                0              0           1       0              2.67  
1                0              0           1       0             47.63  
2                0              0           0       1             14.10  
3                0              0           0       1             59.47  
4                0              0           0       1              1.23  
..             ...            ...         ...     ...               ...  
311              0              0           0       1             76.03  
312              0              0           0       1             65.30  
313              0              0           1       0             52.30  
314              0              0           0       1             26.77  
315              0              0           0       1             24.87  

[316 rows x 20 columns]

In [5]:
blood["Recurrence"].value_counts()

0    262
1     54
Name: Recurrence, dtype: int64

In [10]:
model = smf.logit("Recurrence ~ Age", data = blood)
res = model.fit()
res.summary()

Optimization terminated successfully.
         Current function value: 0.456452
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:             Recurrence   No. Observations:                  316
Model:                          Logit   Df Residuals:                      314
Method:                           MLE   Df Model:                            1
Date:                Thu, 23 Sep 2021   Pseudo R-squ.:                0.001828
Time:                        22:23:12   Log-Likelihood:                -144.24
converged:                       True   LL-Null:                       -144.50
Covariance Type:            nonrobust   LLR p-value:                    0.4673
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -2.5107      1.302     -1.928      0.054      -5.062       0.041
Age            0.0152      0.021      0.723      0.470      -0.026       0.056
==============================================================================
"""

In [11]:
res.params

Intercept   -2.510677
Age          0.015164
dtype: float64

In [14]:
np.exp(res.params)

Intercept    0.081213
Age          1.015279
dtype: float64

In [15]:
model2 = smf.logit("Recurrence ~ Age + PVol + PreopPSA", data = blood)
res2 = model2.fit()
res2.summary()

Optimization terminated successfully.
         Current function value: 0.421375
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:             Recurrence   No. Observations:                  305
Model:                          Logit   Df Residuals:                      301
Method:                           MLE   Df Model:                            3
Date:                Thu, 23 Sep 2021   Pseudo R-squ.:                 0.06660
Time:                        22:27:56   Log-Likelihood:                -128.52
converged:                       True   LL-Null:                       -137.69
Covariance Type:            nonrobust   LLR p-value:                 0.0003744
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -3.7564      1.439     -2.611      0.009      -6.576      -0.937
Age            0.0281      0.024      1.194      0.232      -0.018       0.074
PVol          -0.0080      0.006     -1.368      0.171      -0.019       0.003
PreopPSA       0.0952      0.023      4.128      0.000       0.050       0.140
==============================================================================
"""

In [16]:
np.exp(res2.params)

Intercept    0.023368
Age          1.028542
PVol         0.992061
PreopPSA     1.099839
dtype: float64

In [18]:
model3 = smf.logit("Recurrence ~ Age + PVol + PreopPSA + C(TVol)", data = blood)
res3 = model3.fit()
res3.summary()
np.exp(res3.params)

Optimization terminated successfully.
         Current function value: 0.382324
         Iterations 8


Intercept          0.002155
C(TVol)[T.2.0]     7.948254
C(TVol)[T.3.0]    22.647154
Age                1.026896
PVol               0.999990
PreopPSA           1.060348
dtype: float64

In [20]:
blood.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316 entries, 0 to 315
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   RBC.Age.Group     316 non-null    int64  
 1   Median.RBC.Age    316 non-null    int64  
 2   Age               316 non-null    float64
 3   AA                316 non-null    int64  
 4   FamHx             316 non-null    int64  
 5   PVol              307 non-null    float64
 6   TVol              310 non-null    float64
 7   T.Stage           303 non-null    float64
 8   bGS               314 non-null    float64
 9   BN+               316 non-null    int64  
 10  OrganConfined     316 non-null    int64  
 11  PreopPSA          313 non-null    float64
 12  PreopTherapy      316 non-null    int64  
 13  Units             316 non-null    int64  
 14  sGS               316 non-null    int64  
 15  AnyAdjTherapy     316 non-null    int64  
 16  AdjRadTherapy     316 non-null    int64  
 1

In [21]:
blood_subset = blood[["Recurrence", "Age", "PVol", "PreopPSA", "TVol"]]
blood_subset

Recurrence   Age   PVol  PreopPSA  TVol
0             1  72.1   54.0     14.08   3.0
1             1  73.6   43.2     10.50   3.0
2             0  67.5  102.7      6.98   1.0
3             0  65.8   46.0      4.40   1.0
4             0  63.2   60.0     21.40   2.0
..          ...   ...    ...       ...   ...
311           0  54.8   25.6      5.00   2.0
312           0  62.3   42.3      7.60   2.0
313           1  62.4   50.0      9.30   2.0
314           0  57.6   74.9      4.50   1.0
315           0  59.9   54.1      6.80   3.0

[316 rows x 5 columns]

In [25]:
blood_subset["TVol"] = blood_subset["TVol"].astype("category")
blood_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316 entries, 0 to 315
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   Recurrence  316 non-null    int64   
 1   Age         316 non-null    float64 
 2   PVol        307 non-null    float64 
 3   PreopPSA    313 non-null    float64 
 4   TVol        310 non-null    category
dtypes: category(1), float64(3), int64(1)
memory usage: 10.4 KB


C:\Users\corra\AppData\Local\Temp/ipykernel_12020/1173465625.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  blood_subset["TVol"] = blood_subset["TVol"].astype("category")


In [34]:
blood_sub_dummy = pd.get_dummies(blood_subset, drop_first = True)
blood_sub_dummy = blood_sub_dummy.dropna()
blood_sub_dummy

Recurrence   Age   PVol  PreopPSA  TVol_2.0  TVol_3.0
0             1  72.1   54.0     14.08         0         1
1             1  73.6   43.2     10.50         0         1
2             0  67.5  102.7      6.98         0         0
3             0  65.8   46.0      4.40         0         0
4             0  63.2   60.0     21.40         1         0
..          ...   ...    ...       ...       ...       ...
311           0  54.8   25.6      5.00         1         0
312           0  62.3   42.3      7.60         1         0
313           1  62.4   50.0      9.30         1         0
314           0  57.6   74.9      4.50         0         0
315           0  59.9   54.1      6.80         0         1

[305 rows x 6 columns]

In [35]:
response = blood_sub_dummy["Recurrence"]
response

0      1
1      1
2      0
3      0
4      0
      ..
311    0
312    0
313    1
314    0
315    0
Name: Recurrence, Length: 305, dtype: int64

In [36]:
predictors = blood_sub_dummy.iloc[:, 1:]
predictors

Age   PVol  PreopPSA  TVol_2.0  TVol_3.0
0    72.1   54.0     14.08         0         1
1    73.6   43.2     10.50         0         1
2    67.5  102.7      6.98         0         0
3    65.8   46.0      4.40         0         0
4    63.2   60.0     21.40         1         0
..    ...    ...       ...       ...       ...
311  54.8   25.6      5.00         1         0
312  62.3   42.3      7.60         1         0
313  62.4   50.0      9.30         1         0
314  57.6   74.9      4.50         0         0
315  59.9   54.1      6.80         0         1

[305 rows x 5 columns]

In [53]:
x_train, x_test, y_train, y_test = train_test_split(predictors, response)

NameError: name 'random' is not defined

In [54]:
model = LogisticRegression(penalty = "none")
model.fit(x_train, y_train)

LogisticRegression(penalty='none')

In [55]:
model.coef_

array([[ 0.06976543, -0.01151467,  0.08957498,  0.92826846,  1.82847272]])

In [56]:
model.intercept_

array([-7.24159537])

In [57]:
np.exp(model.coef_)

array([[1.07225663, 0.98855137, 1.09370934, 2.53012436, 6.22437306]])

In [58]:
model.predict(x_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [59]:
y_test.value_counts()

0    66
1    11
Name: Recurrence, dtype: int64

In [60]:
model.score(x_test, y_test)

0.8311688311688312